services:
  - type: web
    name: goalstats-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn goalstats.api-fullstack
    envVars:
      - key: FOOTBALL_API_TOKEN
        value: YOUR_TOKEN
      - key: ODDS_API_KEY
        value: YOUR_ODDS_KEY
      - key: WEATHER_API_KEY
        value: YOUR_WEATHER_KEY
